# Generated by Django 2.0.1 on 2018-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('first_name', 'last_name')},
        ),
    ]
