# Generated by Django 2.0.2 on 2018-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_auto_20180320_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('S', 'Snack'), ('P', 'Play'), ('O', 'Outside'), ('B', 'Bathroom'), ('C', 'CallHome'), ('N', 'Nurse'), ('R', 'Read')], max_length=1),
        ),
    ]
