# Generated by Django 2.0.1 on 2018-04-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_auto_20180320_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
