# Generated by Django 2.0.1 on 2018-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_delete_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('email', 'password1', 'password2')},
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('email', 'password1', 'password2')},
        ),
    ]
